name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Credentials
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/env-timoliacreative.local.gradle.kts
      - name: Run project with Gradle
        run: |
          ./gradlew --warning-mode all run --no-daemon --args="zip-world package"
      - name: release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          files: "zipVersions/*.mcworld"
        env:
          GITHUB_TOKEN: ${{ github.token }}